# Stage 1 - Build

FROM node:22-alpine AS build
WORKDIR /app
COPY . .
RUN npm install && npm run build

# Stage 2 - Production 

FROM nginx:alpine             
COPY --from=build /app/dist /usr/share/nginx/html 
COPY nginx.conf /etc/nginx/conf.d/default.conf
